MySNSTopic:
  Type: AWS::SNS::Topic
  Properties:
    Subscription:
      - Endpoint:
          Fn::GetAtt:
            - "accountQueue"
            - "Arn"
        Protocol: "sqs"
    TopicName: "accountTopic"